export interface Submission {
  id: string;
  crop: string;
  location: string;
  lat: number;
  lng: number;
  date: string;
  riskLevel: 'low' | 'medium' | 'high';
  climaticConditions: string;
  timestamp: number;
}

export type Language = 'en' | 'te' | 'hi' | 'ta' | 'kn' | 'ml';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)' },
  { code: 'ml', name: 'മലയാളം (Malayalam)' }
];

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    title: "Bloom Sync",
    subtitle: "NASA-Powered Agricultural Intelligence",
    farmerPortal: "Farmer Portal",
    mapPortal: "Global Map",
    cropType: "Crop Type",
    location: "Location (City, Region)",
    date: "Target Date",
    analyze: "Analyze Mismatch",
    analyzing: "Processing Satellite Data...",
    riskLevel: "Risk Level",
    mismatch: "Pollination Mismatch",
    yieldRisk: "Yield Risk",
    suggestions: "Expert Suggestions",
    climaticConditions: "Climatic Conditions",
    days: "days",
    low: "Low",
    medium: "Medium",
    high: "High",
    alternativeCrops: "Alternative Crops",
    autoPollination: "Auto-Pollination Solutions",
    mapZones: "Risk Zones",
    redZone: "Red Zone (High Risk)",
    yellowZone: "Yellow Zone (Medium Risk)",
    greenZone: "Green Zone (Safe)",
    recentSubmissions: "Recent Submissions",
    language: "Language",
    nasaScientistView: "Scientist Dashboard",
    voiceInput: "Voice Input",
    listening: "Listening...",
    stopListening: "Stop",
    voiceAssistant: "Voice Assistant"
  },
  te: {
    title: "బ్లూమ్ సింక్ (Bloom Sync)",
    subtitle: "నాసా ఆధారిత వ్యవసాయ మేధస్సు",
    farmerPortal: "రైతు పోర్టల్",
    mapPortal: "ప్రపంచ పటం",
    cropType: "పంట రకం",
    location: "ప్రాంతం (నగరం, ప్రాంతం)",
    date: "తేదీ",
    analyze: "విశ్లేషించు",
    analyzing: "శాటిలైట్ డేటాను విశ్లేషిస్తోంది...",
    riskLevel: "ప్రమాద స్థాయి",
    mismatch: "పరాగసంపర్క అసమతుల్యత",
    yieldRisk: "దిగుబడి ప్రమాదం",
    suggestions: "నిపుణుల సూచనలు",
    climaticConditions: "వాతావరణ పరిస్థితులు",
    days: "రోజులు",
    low: "తక్కువ",
    medium: "మధ్యస్థం",
    high: "ఎక్కువ",
    alternativeCrops: "ప్రత్యామ్నాయ పంటలు",
    autoPollination: "ఆటో-పరాగసంపర్క పరిష్కారాలు",
    mapZones: "ప్రమాద మండలాలు",
    redZone: "రెడ్ జోన్ (అధిక ప్రమాదం)",
    yellowZone: "ఎల్లో జోన్ (మధ్యస్థ ప్రమాదం)",
    greenZone: "గ్రీన్ జోన్ (సురక్షితం)",
    recentSubmissions: "ఇటీవలి సమర్పణలు",
    language: "భాష",
    nasaScientistView: "శాస్త్రవేత్త డాష్‌బోర్డ్",
    voiceInput: "వాయిస్ ఇన్పుట్",
    listening: "వింటున్నాను...",
    stopListening: "ఆపు",
    voiceAssistant: "వాయిస్ అసిస్టెంట్"
  },
  hi: {
    title: "ब्लूम सिंक (Bloom Sync)",
    subtitle: "नासा-संचालित कृषि खुफिया",
    farmerPortal: "किसान पोर्टल",
    mapPortal: "वैश्विक मानचित्र",
    cropType: "फसल का प्रकार",
    location: "स्थान (शहर, क्षेत्र)",
    date: "लक्ष्य तिथि",
    analyze: "विश्लेषण करें",
    analyzing: "सैटेलाइट डेटा संसाधित कर रहा है...",
    riskLevel: "जोखिम स्तर",
    mismatch: "परागण बेमेल",
    yieldRisk: "उपज जोखिम",
    suggestions: "विशेषज्ञ सुझाव",
    climaticConditions: "जलवायु परिस्थितियां",
    days: "दिन",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    alternativeCrops: "वैकल्पिक फसलें",
    autoPollination: "ऑटो-परागण समाधान",
    mapZones: "जोखिम क्षेत्र",
    redZone: "रेड ज़ोन (उच्च जोखिम)",
    yellowZone: "येलो ज़ोन (मध्यम जोखिम)",
    greenZone: "ग्रीन ज़ोन (सुरक्षित)",
    recentSubmissions: "हालिया सबमिशन",
    language: "भाषा",
    nasaScientistView: "वैज्ञानिक डैशबोर्ड",
    voiceInput: "आवाज इनपुट",
    listening: "सुन रहा हूँ...",
    stopListening: "रोकें",
    voiceAssistant: "वॉयस असिस्टेंट"
  },
  ta: {
    title: "ப்ளூம் சிங்க் (Bloom Sync)",
    subtitle: "நாசா-இயங்கும் விவசாய நுண்ணறிவு",
    farmerPortal: "விவசாயி போர்டல்",
    mapPortal: "உலகளாவிய வரைபடம்",
    cropType: "பயிர் வகை",
    location: "இடம் (நகரம், பிராந்தியம்)",
    date: "இலக்கு தேதி",
    analyze: "பகுப்பாய்வு செய்",
    analyzing: "செயற்கைக்கோள் தரவைச் செயலாக்குகிறது...",
    riskLevel: "ஆபத்து நிலை",
    mismatch: "மகரந்தச் சேர்க்கை பொருத்தமின்மை",
    yieldRisk: "மகசூல் ஆபத்து",
    suggestions: "நிபுணர் பரிந்துரைகள்",
    climaticConditions: "காலநிலை நிலைமைகள்",
    days: "நாட்கள்",
    low: "குறைந்த",
    medium: "நடுத்தர",
    high: "அதிக",
    alternativeCrops: "மாற்று பயிர்கள்",
    autoPollination: "தானியங்கி மகரந்தச் சேர்க்கை தீர்வுகள்",
    mapZones: "ஆபத்து மண்டலங்கள்",
    redZone: "சிவப்பு மண்டலம் (அதிக ஆபத்து)",
    yellowZone: "மஞ்சள் மண்டலம் (நடுத்தர ஆபத்து)",
    greenZone: "பச்சை மண்டலம் (பாதுகாப்பானது)",
    recentSubmissions: "சமீபத்திய சமர்ப்பிப்புகள்",
    language: "மொழி",
    nasaScientistView: "விஞ்ஞானி டாஷ்போர்டு",
    voiceInput: "குரல் உள்ளீடு",
    listening: "கேட்கிறது...",
    stopListening: "நிறுத்து",
    voiceAssistant: "குரல் உதவியாளர்"
  },
  kn: {
    title: "ಬ್ಲೂಮ್ ಸಿಂಕ್ (Bloom Sync)",
    subtitle: "ನಾಸಾ-ಚಾಲಿತ ಕೃಷಿ ಬುದ್ಧಿವಂತಿಕೆ",
    farmerPortal: "ರೈತ ಪೋರ್ಟಲ್",
    mapPortal: "ಜಾಗತಿಕ ನಕ್ಷೆ",
    cropType: "ಬೆಳೆ ಪ್ರಕಾರ",
    location: "ಸ್ಥಳ (ನಗರ, ಪ್ರದೇಶ)",
    date: "ಗುರಿ ದಿನಾಂಕ",
    analyze: "ವಿಶ್ಲೇಷಿಸಿ",
    analyzing: "ಉಪಗ್ರಹ ಡೇಟಾವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    riskLevel: "ಅಪಾಯದ ಮಟ್ಟ",
    mismatch: "ಪರಾಗಸ್ಪರ್ಶ ಅಸಮತೋಲನ",
    yieldRisk: "ಇಳುವರಿ ಅಪಾಯ",
    suggestions: "ತಜ್ಞರ ಸಲಹೆಗಳು",
    climaticConditions: "ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿಗಳು",
    days: "ದಿನಗಳು",
    low: "ಕಡಿಮೆ",
    medium: "ಮಧ್ಯಮ",
    high: "ಹೆಚ್ಚು",
    alternativeCrops: "ಪರ್ಯಾಯ ಬೆಳೆಗಳು",
    autoPollination: "ಸ್ವಯಂ-ಪರಾಗಸ್ಪರ್ಶ ಪರಿಹಾರಗಳು",
    mapZones: "ಅಪಾಯದ ವಲಯಗಳು",
    redZone: "ಕೆಂಪು ವಲಯ (ಹೆಚ್ಚಿನ ಅಪಾಯ)",
    yellowZone: "ಹಳದಿ ವಲಯ (ಮಧ್ಯಮ ಅಪಾಯ)",
    greenZone: "ಹಸಿರು ವಲಯ (ಸುರಕ್ಷಿತ)",
    recentSubmissions: "ಇತ್ತೀಚಿನ ಸಲ್ಲಿಕೆಗಳು",
    language: "ಭಾಷೆ",
    nasaScientistView: "ವಿಜ್ಞಾನಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    voiceInput: "ಧ್ವನಿ ಇನ್‌ಪುಟ್",
    listening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...",
    stopListening: "ನಿಲ್ಲಿಸು",
    voiceAssistant: "ಧ್ವನಿ ಸಹಾಯಕ"
  },
  ml: {
    title: "ബ്ലൂം സിങ്ക് (Bloom Sync)",
    subtitle: "നാസ അധിഷ്ഠിത കാർഷിക ഇന്റലിജൻസ്",
    farmerPortal: "കർഷക പോർട്ടൽ",
    mapPortal: "ആഗോള ഭൂപടം",
    cropType: "വിള തരം",
    location: "സ്ഥലം (നഗരം, പ്രദേശം)",
    date: "ലക്ഷ്യ തീയതി",
    analyze: "വിശകലനം ചെയ്യുക",
    analyzing: "സാറ്റലൈറ്റ് ഡാറ്റ പ്രോസസ്സ് ചെയ്യുന്നു...",
    riskLevel: "അപകടസാധ്യത നില",
    mismatch: "പരാഗണത്തിലെ പൊരുത്തക്കേട്",
    yieldRisk: "വിളവ് അപകടസാധ്യത",
    suggestions: "വിദഗ്ദ്ധ നിർദ്ദേശങ്ങൾ",
    climaticConditions: "കാലാവസ്ഥാ സാഹചര്യങ്ങൾ",
    days: "ദിവസങ്ങൾ",
    low: "കുറഞ്ഞ",
    medium: "മിതമായ",
    high: "ഉയർന്ന",
    alternativeCrops: "ബദൽ വിളകൾ",
    autoPollination: "ഓട്ടോ-പരാഗണ പരിഹാരങ്ങൾ",
    mapZones: "അപകടസാധ്യത മേഖലകൾ",
    redZone: "റെഡ് സോൺ (ഉയർന്ന അപകടസാധ്യത)",
    yellowZone: "യല്ലോ സോൺ (മിതമായ അപകടസാധ്യത)",
    greenZone: "ഗ്രീൻ സോൺ (സുരക്ഷിതം)",
    recentSubmissions: "സമീപകാല സമർപ്പണങ്ങൾ",
    language: "ഭാഷ",
    nasaScientistView: "സയന്റിസ്റ്റ് ഡാഷ്‌ബോർഡ്",
    voiceInput: "വോയ്‌സ് ഇൻപുട്ട്",
    listening: "ശ്രദ്ധിക്കുന്നു...",
    stopListening: "നിർത്തുക",
    voiceAssistant: "വോയ്‌സ് അസിസ്റ്റന്റ്"
  }
};
