export interface Submission {
  id: string;
  crop: string;
  location: string;
  lat: number;
  lng: number;
  date: string;
  riskLevel: 'low' | 'medium' | 'high';
  climaticConditions: string;
  timestamp: number;
}

export type Language = 'en' | 'te' | 'hi' | 'ta' | 'kn' | 'ml';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'te', name: 'తెలుగు (Telugu)' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
  { code: 'kn', name: 'ಕನ್ನಡ (Kannada)' },
  { code: 'ml', name: 'മലയാളം (Malayalam)' }
];

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    title: "Bloom Sync",
    subtitle: "NASA-Powered Agricultural Intelligence",
    farmerPortal: "Farmer Portal",
    mapPortal: "Global Map",
    cropType: "Crop Type",
    location: "Location (City, Region)",
    date: "Target Date",
    analyze: "Analyze Mismatch",
    analyzing: "Processing Satellite Data...",
    riskLevel: "Risk Level",
    mismatch: "Pollination Mismatch",
    yieldRisk: "Yield Risk",
    suggestions: "Expert Suggestions",
    climaticConditions: "Climatic Conditions",
    days: "days",
    low: "Low",
    medium: "Medium",
    high: "High",
    alternativeCrops: "Alternative Crops",
    autoPollination: "Auto-Pollination Solutions",
    mapZones: "Risk Zones",
    redZone: "Red Zone (High Risk)",
    yellowZone: "Yellow Zone (Medium Risk)",
    greenZone: "Green Zone (Safe)",
    recentSubmissions: "Recent Submissions",
    language: "Language",
    nasaScientistView: "Scientist Dashboard",
    adminPortal: "Admin Analytics",
    historyPortal: "Records History",
    viewAnalysis: "View Analysis",
    noRecords: "No records found.",
    voiceInput: "Voice Input",
    whatMayHappen: "What may happen",
    expectedYield: "Expected Yield",
    optionA: "Option A – Change Crop",
    optionB: "Option B – Continue Same Crop",
    changeCropSuggestion: "Suggest safer alternative crops for this season.",
    continueCropSteps: "Practical precaution steps in simple language.",
    selectChoice: "Select your decision:",
    choiceSelected: "Choice recorded. Thank you!",
    adminStats: "System-wide Analytics",
    totalSubmissions: "Total Submissions",
    riskDistribution: "Risk Distribution",
    farmerChoices: "Farmer Decisions",
    cropPopularity: "Crop Popularity",
    exportData: "Export Data (CSV)",
    filters: "Filters",
    applyFilters: "Apply Filters",
    resetFilters: "Reset",
    riskLevelFilter: "Risk Level",
    cropFilter: "Crop",
    dateRange: "Date Range",
    listening: "Listening...",
    stopListening: "Stop",
    voiceAssistant: "Voice Assistant",
    climateIntelligence: "Global Climate Intelligence",
    farmerAdvisory: "Local Farmer Advisory",
    riskScore: "Risk Score",
    yieldImpact: "Yield Impact",
    stageRecommendations: "Stage Recommendations",
    actionableSteps: "Actionable Steps",
    tempAnomaly: "Temp Anomaly",
    ndviTrend: "NDVI Trend",
    rainfallAnomaly: "Rainfall Anomaly",
    climateSignal: "Climate Signal",
    autoVoiceAlert: "High Risk Detected! Playing Advisory..."
  },
  te: {
    title: "బ్లూమ్ సింక్ (Bloom Sync)",
    subtitle: "నాసా ఆధారిత వ్యవసాయ మేధస్సు",
    farmerPortal: "రైతు పోర్టల్",
    mapPortal: "ప్రపంచ పటం",
    cropType: "పంట రకం",
    location: "ప్రాంతం (నగరం, ప్రాంతం)",
    date: "తేదీ",
    analyze: "విశ్లేషించు",
    analyzing: "శాటిలైట్ డేటాను విశ్లేషిస్తోంది...",
    riskLevel: "ప్రమాద స్థాయి",
    mismatch: "పరాగసంపర్క అసమతుల్యత",
    yieldRisk: "దిగుబడి ప్రమాదం",
    suggestions: "నిపుణుల సూచనలు",
    climaticConditions: "వాతావరణ పరిస్థితులు",
    days: "రోజులు",
    low: "తక్కువ",
    medium: "మధ్యస్థం",
    high: "ఎక్కువ",
    alternativeCrops: "ప్రత్యామ్నాయ పంటలు",
    autoPollination: "ఆటో-పరాగసంపర్క పరిష్కారాలు",
    mapZones: "ప్రమాద మండలాలు",
    redZone: "రెడ్ జోన్ (అధిక ప్రమాదం)",
    yellowZone: "ఎల్లో జోన్ (మధ్యస్థ ప్రమాదం)",
    greenZone: "గ్రీన్ జోన్ (సురక్షితం)",
    recentSubmissions: "ఇటీవలి సమర్పణలు",
    language: "భాష",
    nasaScientistView: "శాస్త్రవేత్త డాష్‌బోర్డ్",
    adminPortal: "అడ్మిన్ అనలిటిక్స్",
    historyPortal: "రికార్డుల చరిత్ర",
    viewAnalysis: "విశ్లేషణను చూడండి",
    noRecords: "రికార్డులు ఏవీ లేవు.",
    voiceInput: "వాయిస్ ఇన్పుట్",
    whatMayHappen: "ఏమి జరగవచ్చు",
    expectedYield: "ఆశించిన దిగుబడి",
    optionA: "ఎంపిక A – పంట మార్చండి",
    optionB: "ఎంపిక B – అదే పంటను కొనసాగించండి",
    changeCropSuggestion: "ఈ సీజన్ కోసం సురక్షితమైన ప్రత్యామ్నాయ పంటలను సూచించండి.",
    continueCropSteps: "సరళమైన భాషలో ఆచరణాత్మక జాగ్రత్తలు.",
    selectChoice: "మీ నిర్ణయాన్ని ఎంచుకోండి:",
    choiceSelected: "నిర్ణయం రికార్డ్ చేయబడింది. ధన్యవాదాలు!",
    adminStats: "సిస్టమ్-వైడ్ అనలిటిక్స్",
    totalSubmissions: "మొత్తం సమర్పణలు",
    riskDistribution: "రిస్క్ పంపిణీ",
    farmerChoices: "రైతు నిర్ణయాలు",
    cropPopularity: "పంట ప్రజాదరణ",
    exportData: "డేటాను ఎగుమతి చేయండి (CSV)",
    filters: "ఫిల్టర్లు",
    applyFilters: "ఫిల్టర్లను వర్తింపజేయండి",
    resetFilters: "రీసెట్",
    riskLevelFilter: "రిస్క్ స్థాయి",
    cropFilter: "పంట",
    dateRange: "తేదీ పరిధి",
    listening: "వింటున్నాను...",
    stopListening: "ఆపు",
    voiceAssistant: "వాయిస్ అసిస్టెంట్"
  },
  hi: {
    title: "ब्लूम सिंक (Bloom Sync)",
    subtitle: "नासा-संचालित कृषि खुफिया",
    farmerPortal: "किसान पोर्टल",
    mapPortal: "वैश्विक मानचित्र",
    cropType: "फसल का प्रकार",
    location: "स्थान (शहर, क्षेत्र)",
    date: "लक्ष्य तिथि",
    analyze: "विश्लेषण करें",
    analyzing: "सैटेलाइट डेटा संसाधित कर रहा है...",
    riskLevel: "जोखिम स्तर",
    mismatch: "परागण बेमेल",
    yieldRisk: "उपज जोखिम",
    suggestions: "विशेषज्ञ सुझाव",
    climaticConditions: "जलवायु परिस्थितियां",
    days: "दिन",
    low: "कम",
    medium: "मध्यम",
    high: "उच्च",
    alternativeCrops: "वैकल्पिक फसलें",
    autoPollination: "ऑटो-परागण समाधान",
    mapZones: "जोखिम क्षेत्र",
    redZone: "रेड ज़ोन (उच्च जोखिम)",
    yellowZone: "येलो ज़ोन (मध्यम जोखिम)",
    greenZone: "ग्रीन ज़ोन (सुरक्षित)",
    recentSubmissions: "हालिया सबमिशन",
    language: "भाषा",
    nasaScientistView: "वैज्ञानिक डैशबोर्ड",
    adminPortal: "एडमिन एनालिटिक्स",
    historyPortal: "रिकॉर्ड इतिहास",
    viewAnalysis: "विश्लेषण देखें",
    noRecords: "कोई रिकॉर्ड नहीं मिला।",
    voiceInput: "आवाज इनपुट",
    whatMayHappen: "क्या हो सकता है",
    expectedYield: "अपेक्षित उपज",
    optionA: "विकल्प A - फसल बदलें",
    optionB: "विकल्प B - वही फसल जारी रखें",
    changeCropSuggestion: "इस मौसम के लिए सुरक्षित वैकल्पिक फसलों का सुझाव दें।",
    continueCropSteps: "सरल भाषा में व्यावहारिक सावधानी के कदम।",
    selectChoice: "अपना निर्णय चुनें:",
    choiceSelected: "विकल्प रिकॉर्ड किया गया। धन्यवाद!",
    adminStats: "सिस्टम-व्यापी विश्लेषण",
    totalSubmissions: "कुल सबमिशन",
    riskDistribution: "जोखिम वितरण",
    farmerChoices: "किसान निर्णय",
    cropPopularity: "फसल लोकप्रियता",
    exportData: "डेटा निर्यात करें (CSV)",
    filters: "फ़िल्टर",
    applyFilters: "फ़िल्टर लागू करें",
    resetFilters: "रीसेट",
    riskLevelFilter: "जोखिम स्तर",
    cropFilter: "फसल",
    dateRange: "दिनांक सीमा",
    listening: "सुन रहा हूँ...",
    stopListening: "रोकें",
    voiceAssistant: "वॉयस असिस्टेंट",
    climateIntelligence: "वैश्विक जलवायु खुफिया",
    farmerAdvisory: "स्थानीय किसान सलाहकार",
    riskScore: "जोखिम स्कोर",
    yieldImpact: "उपज प्रभाव",
    stageRecommendations: "चरण सिफारिशें",
    actionableSteps: "कार्रवाई योग्य कदम",
    tempAnomaly: "तापमान विसंगति",
    ndviTrend: "NDVI रुझान",
    rainfallAnomaly: "वर्षा विसंगति",
    climateSignal: "जलवायु संकेत",
    autoVoiceAlert: "उच्च जोखिम का पता चला! सलाहकार बजा रहा है..."
  },
  ta: {
    title: "ப்ளூம் சிங்க் (Bloom Sync)",
    subtitle: "நாசா-இயங்கும் விவசாய நுண்ணறிவு",
    farmerPortal: "விவசாயி போர்டல்",
    mapPortal: "உலகளாவிய வரைபடம்",
    cropType: "பயிர் வகை",
    location: "இடம் (நகரம், பிராந்தியம்)",
    date: "இலக்கு தேதி",
    analyze: "பகுப்பாய்வு செய்",
    analyzing: "செயற்கைக்கோள் தரவைச் செயலாக்குகிறது...",
    riskLevel: "ஆபத்து நிலை",
    mismatch: "மகரந்தச் சேர்க்கை பொருத்தமின்மை",
    yieldRisk: "மகசூல் ஆபத்து",
    suggestions: "நிபுணர் பரிந்துரைகள்",
    climaticConditions: "காலநிலை நிலைமைகள்",
    days: "நாட்கள்",
    low: "குறைந்த",
    medium: "நடுத்தர",
    high: "அதிக",
    alternativeCrops: "மாற்று பயிர்கள்",
    autoPollination: "தானியங்கி மகரந்தச் சேர்க்கை தீர்வுகள்",
    mapZones: "ஆபத்து மண்டலங்கள்",
    redZone: "சிவப்பு மண்டலம் (அதிக ஆபத்து)",
    yellowZone: "மஞ்சள் மண்டலம் (நடுத்தர ஆபத்து)",
    greenZone: "பச்சை மண்டலம் (பாதுகாப்பானது)",
    recentSubmissions: "சமீபத்திய சமர்ப்பிப்புகள்",
    language: "மொழி",
    nasaScientistView: "விஞ்ஞானி டாஷ்போர்டு",
    adminPortal: "நிர்வாக பகுப்பாய்வு",
    historyPortal: "பதிவு வரலாறு",
    viewAnalysis: "பகுப்பாய்வைக் காண்க",
    noRecords: "பதிவுகள் எதுவும் இல்லை.",
    voiceInput: "குரல் உள்ளீடு",
    whatMayHappen: "என்ன நடக்கலாம்",
    expectedYield: "எதிர்பார்க்கப்படும் மகசூல்",
    optionA: "விருப்பம் A – பயிரை மாற்றவும்",
    optionB: "விருப்பம் B – அதே பயிரைத் தொடரவும்",
    changeCropSuggestion: "இந்த பருவத்திற்கு பாதுகாப்பான மாற்று பயிர்களை பரிந்துரைக்கவும்.",
    continueCropSteps: "எளிய மொழியில் நடைமுறை முன்னெச்சரிக்கை நடவடிக்கைகள்.",
    selectChoice: "உங்கள் முடிவைத் தேர்ந்தெடுக்கவும்:",
    choiceSelected: "விருப்பம் பதிவு செய்யப்பட்டது. நன்றி!",
    adminStats: "அமைப்பு அளவிலான பகுப்பாய்வு",
    totalSubmissions: "மொத்த சமர்ப்பிப்புகள்",
    riskDistribution: "ஆபத்து விநியோகம்",
    farmerChoices: "விவசாயி முடிவுகள்",
    cropPopularity: "பயிர் புகழ்",
    exportData: "தரவை ஏற்றுமதி செய் (CSV)",
    filters: "வடிகட்டிகள்",
    applyFilters: "வடிகட்டிகளைப் பயன்படுத்து",
    resetFilters: "மீட்டமை",
    riskLevelFilter: "ஆபத்து நிலை",
    cropFilter: "பயிர்",
    dateRange: "தேதி வரம்பு",
    listening: "கேட்கிறது...",
    stopListening: "நிறுத்து",
    voiceAssistant: "குரல் உதவியாளர்",
    climateIntelligence: "உலகளாவிய காலநிலை நுண்ணறிவு",
    farmerAdvisory: "உள்ளூர் விவசாயி ஆலோசனை",
    riskScore: "ஆபத்து மதிப்பெண்",
    yieldImpact: "மகசூல் பாதிப்பு",
    stageRecommendations: "நிலை பரிந்துரைகள்",
    actionableSteps: "செயல்படக்கூடிய படிகள்",
    tempAnomaly: "வெப்பநிலை ஒழுங்கின்மை",
    ndviTrend: "NDVI போக்கு",
    rainfallAnomaly: "மழைப்பொழிவு ஒழுங்கின்மை",
    climateSignal: "காலநிலை சமிக்ஞை",
    autoVoiceAlert: "அதிக ஆபத்து கண்டறியப்பட்டது! ஆலோசனையை இயக்குகிறது..."
  },
  kn: {
    title: "ಬ್ಲೂಮ್ ಸಿಂಕ್ (Bloom Sync)",
    subtitle: "ನಾಸಾ-ಚಾಲಿತ ಕೃಷಿ ಬುದ್ಧಿವಂತಿಕೆ",
    farmerPortal: "ರೈತ ಪೋರ್ಟಲ್",
    mapPortal: "ಜಾಗತಿಕ ನಕ್ಷೆ",
    cropType: "ಬೆಳೆ ಪ್ರಕಾರ",
    location: "ಸ್ಥಳ (ನಗರ, ಪ್ರದೇಶ)",
    date: "ಗುರಿ ದಿನಾಂಕ",
    analyze: "ವಿಶ್ಲೇಷಿಸಿ",
    analyzing: "ಉಪಗ್ರಹ ಡೇಟಾವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    riskLevel: "ಅಪಾಯದ ಮಟ್ಟ",
    mismatch: "ಪರಾಗಸ್ಪರ್ಶ ಅಸಮತೋಲನ",
    yieldRisk: "ಇಳುವರಿ ಅಪಾಯ",
    suggestions: "ತಜ್ಞರ ಸಲಹೆಗಳು",
    climaticConditions: "ಹವಾಮಾನ ಪರಿಸ್ಥಿತಿಗಳು",
    days: "ದಿನಗಳು",
    low: "ಕಡಿಮೆ",
    medium: "ಮಧ್ಯಮ",
    high: "ಹೆಚ್ಚು",
    alternativeCrops: "ಪರ್ಯಾಯ ಬೆಳೆಗಳು",
    autoPollination: "ಸ್ವಯಂ-ಪರಾಗಸ್ಪರ್ಶ ಪರಿಹಾರಗಳು",
    mapZones: "ಅಪಾಯದ ವಲಯಗಳು",
    redZone: "ಕೆಂಪು ವಲಯ (ಹೆಚ್ಚಿನ ಅಪಾಯ)",
    yellowZone: "ಹಳದಿ ವಲಯ (ಮಧ್ಯಮ ಅಪಾಯ)",
    greenZone: "ಹಸಿರು ವಲಯ (ಸುರಕ್ಷಿತ)",
    recentSubmissions: "ಇತ್ತೀಚಿನ ಸಲ್ಲಿಕೆಗಳು",
    language: "ಭಾಷೆ",
    nasaScientistView: "ವಿಜ್ಞಾನಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    adminPortal: "ನಿರ್ವಾಹಕ ವಿಶ್ಲೇಷಣೆ",
    historyPortal: "ದಾಖಲೆಗಳ ಇತಿಹಾಸ",
    viewAnalysis: "ವಿಶ್ಲೇಷಣೆಯನ್ನು ವೀಕ್ಷಿಸಿ",
    noRecords: "ಯಾವುದೇ ದಾಖಲೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
    voiceInput: "ಧ್ವನಿ ಇನ್‌ಪುಟ್",
    whatMayHappen: "ಏನು ಸಂಭವಿಸಬಹುದು",
    expectedYield: "ನಿರೀಕ್ಷಿತ ಇಳುವರಿ",
    optionA: "ಆಯ್ಕೆ A – ಬೆಳೆ ಬದಲಾಯಿಸಿ",
    optionB: "ಆಯ್ಕೆ B – ಅದೇ ಬೆಳೆಯನ್ನು ಮುಂದುವರಿಸಿ",
    changeCropSuggestion: "ಈ ಹಂಗಾಮಿಗೆ ಸುರಕ್ಷಿತ ಪರ್ಯಾಯ ಬೆಳೆಗಳನ್ನು ಸೂಚಿಸಿ.",
    continueCropSteps: "ಸರಳ ಭಾಷೆಯಲ್ಲಿ ಪ್ರಾಯೋಗಿಕ ಮುನ್ನೆಚ್ಚರಿಕೆ ಕ್ರಮಗಳು.",
    selectChoice: "ನಿಮ್ಮ ನಿರ್ಧಾರವನ್ನು ಆರಿಸಿ:",
    choiceSelected: "ಆಯ್ಕೆಯನ್ನು ದಾಖಲಿಸಲಾಗಿದೆ. ಧನ್ಯವಾದಗಳು!",
    adminStats: "ಸಿಸ್ಟಮ್-ವೈಡ್ ಅನಾಲಿಟಿಕ್ಸ್",
    totalSubmissions: "ಒಟ್ಟು ಸಲ್ಲಿಕೆಗಳು",
    riskDistribution: "ಅಪಾಯದ ವಿತರಣೆ",
    farmerChoices: "ರೈತರ ನಿರ್ಧಾರಗಳು",
    cropPopularity: "ಬೆಳೆ ಜನಪ್ರಿಯತೆ",
    exportData: "ಡೇಟಾವನ್ನು ರಫ್ತು ಮಾಡಿ (CSV)",
    filters: "ಫಿಲ್ಟರ್‌ಗಳು",
    applyFilters: "ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ",
    resetFilters: "ಮರುಹೊಂದಿಸಿ",
    riskLevelFilter: "ಅಪಾಯದ ಮಟ್ಟ",
    cropFilter: "ಬೆಳೆ",
    dateRange: "ದಿನಾಂಕ ಶ್ರೇಣಿ",
    listening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...",
    stopListening: "ನಿಲ್ಲಿಸು",
    voiceAssistant: "ಧ್ವನಿ ಸಹಾಯಕ",
    climateIntelligence: "ಜಾಗತಿಕ ಹವಾಮಾನ ಬುದ್ಧಿವಂತಿಕೆ",
    farmerAdvisory: "ಸ್ಥಳೀಯ ರೈತ ಸಲಹೆ",
    riskScore: "ಅಪಾಯದ ಅಂಕ",
    yieldImpact: "ಇಳುವರಿ ಪರಿಣಾಮ",
    stageRecommendations: "ಹಂತದ ಶಿಫಾರಸುಗಳು",
    actionableSteps: "ಕಾರ್ಯಗತಗೊಳಿಸಬಹುದಾದ ಕ್ರಮಗಳು",
    tempAnomaly: "ತಾಪಮಾನ ವೈಪರೀತ್ಯ",
    ndviTrend: "NDVI ಪ್ರವೃತ್ತಿ",
    rainfallAnomaly: "ಮಳೆ ವೈಪರೀತ್ಯ",
    climateSignal: "ಹವಾಮಾನ ಸಂಕೇತ",
    autoVoiceAlert: "ಹೆಚ್ಚಿನ ಅಪಾಯ ಪತ್ತೆಯಾಗಿದೆ! ಸಲಹೆಯನ್ನು ಪ್ಲೇ ಮಾಡಲಾಗುತ್ತಿದೆ..."
  },
  ml: {
    title: "ബ്ലൂം സിങ്ക് (Bloom Sync)",
    subtitle: "നാസ അധിഷ്ഠിത കാർഷിക ഇന്റലിജൻസ്",
    farmerPortal: "കർഷക പോർട്ടൽ",
    mapPortal: "ആഗോള ഭൂപടം",
    cropType: "വിള തരം",
    location: "സ്ഥലം (നഗരം, പ്രദേശം)",
    date: "ലക്ഷ്യ തീയതി",
    analyze: "വിശകലനം ചെയ്യുക",
    analyzing: "സാറ്റലൈറ്റ് ഡാറ്റ പ്രോസസ്സ് ചെയ്യുന്നു...",
    riskLevel: "അപകടസാധ്യത നില",
    mismatch: "പരാഗണത്തിലെ പൊരുത്തക്കേട്",
    yieldRisk: "വിളവ് അപകടസാധ്യത",
    suggestions: "വിദഗ്ദ്ധ നിർദ്ദേശങ്ങൾ",
    climaticConditions: "കാലാവസ്ഥാ സാഹചര്യങ്ങൾ",
    days: "ദിവസങ്ങൾ",
    low: "കുറഞ്ഞ",
    medium: "മിതമായ",
    high: "ഉയർന്ന",
    alternativeCrops: "ബദൽ വിളകൾ",
    autoPollination: "ഓട്ടോ-പരാഗണ പരിഹാരങ്ങൾ",
    mapZones: "അപകടസാധ്യത മേഖലകൾ",
    redZone: "റെഡ് സോൺ (ഉയർന്ന അപകടസാധ്യത)",
    yellowZone: "യല്ലോ സോൺ (മിതമായ അപകടസാധ്യത)",
    greenZone: "ഗ്രീൻ സോൺ (സുരക്ഷിതം)",
    recentSubmissions: "സമീപകാല സമർപ്പണങ്ങൾ",
    language: "ഭാഷ",
    nasaScientistView: "സയന്റിസ്റ്റ് ഡാഷ്‌ബോർഡ്",
    adminPortal: "അഡ്മിൻ അനലിറ്റിക്സ്",
    historyPortal: "റെക്കോർഡ് ഹിസ്റ്ററി",
    viewAnalysis: "വിശകലനം കാണുക",
    noRecords: "റെക്കോർഡുകളൊന്നും കണ്ടെത്തിയില്ല.",
    voiceInput: "വോയ്‌സ് ഇൻപുട്ട്",
    whatMayHappen: "എന്ത് സംഭവിക്കാം",
    expectedYield: "പ്രതീക്ഷിക്കുന്ന വിളവ്",
    optionA: "ഓപ്ഷൻ A – വിള മാറ്റുക",
    optionB: "ഓപ്ഷൻ B – അതേ വിള തുടരുക",
    changeCropSuggestion: "ഈ സീസണിലേക്ക് സുരക്ഷിതമായ ബദൽ വിളകൾ നിർദ്ദേശിക്കുക.",
    continueCropSteps: "ലളിതമായ ഭാഷയിൽ പ്രായോഗിക മുൻകരുതൽ നടപടികൾ.",
    selectChoice: "നിങ്ങളുടെ തീരുമാനം തിരഞ്ഞെടുക്കുക:",
    choiceSelected: "തീരുമാനം രേഖപ്പെടുത്തി. നന്ദി!",
    adminStats: "സിസ്റ്റം-വൈഡ് അനലിറ്റിക്സ്",
    totalSubmissions: "ആകെ സമർപ്പണങ്ങൾ",
    riskDistribution: "അപകടസാധ്യത വിതരണം",
    farmerChoices: "കർഷക തീരുമാനങ്ങൾ",
    cropPopularity: "വിളകളുടെ ജനപ്രീതി",
    exportData: "ഡാറ്റ എക്‌സ്‌പോർട്ട് ചെയ്യുക (CSV)",
    filters: "ഫിൽട്ടറുകൾ",
    applyFilters: "ഫിൽട്ടറുകൾ പ്രയോഗിക്കുക",
    resetFilters: "റീസെറ്റ്",
    riskLevelFilter: "അപകടസാധ്യത നില",
    cropFilter: "വിള",
    dateRange: "തീയതി പരിധി",
    listening: "ശ്രദ്ധിക്കുന്നു...",
    stopListening: "നിർത്തുക",
    voiceAssistant: "വോയ്‌സ് അസിസ്റ്റന്റ്",
    climateIntelligence: "ആഗോള കാലാവസ്ഥാ ഇന്റലിജൻസ്",
    farmerAdvisory: "പ്രാദേശിക കർഷക ഉപദേശം",
    riskScore: "അപകടസാಧ്യത സ്കോർ",
    yieldImpact: "വിളവ് ആഘാതം",
    stageRecommendations: "ഘട്ട ശുപാർശകൾ",
    actionableSteps: "പ്രവർത്തനക്ഷമമായ നടപടികൾ",
    tempAnomaly: "താപനില അപാകത",
    ndviTrend: "NDVI പ്രവണത",
    rainfallAnomaly: "മഴയുടെ അപാകത",
    climateSignal: "കാലാവസ്ഥാ സിഗ്നൽ",
    autoVoiceAlert: "ഉയർന്ന അപകടസാധ്യത കണ്ടെത്തി! ഉപദേശം പ്ലേ ചെയ്യുന്നു..."
  }
};
